[package]
name = "drogue-cloud-http-endpoint"
version = "0.4.0"
authors = ["Jens Reimann <jreimann@redhat.com>", "Dejan Bosanac <dbosanac@redhat.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]

anyhow = "1"
snafu = "0.6"
async-trait = "0.1"

#actix = "0.10"
#actix-broker = "0.3.1"
#actix-rt = "1.1"
#actix-service = "1"
#actix-tls = "2"
#actix-web = "3"
#actix-web-httpauth = "0.5.0"
#actix-web-actors = "3"

#actix = "0.10"
actix-broker = "0.4.0-beta.1"
actix-rt = "2"
#actix-service = "1"
actix-tls = "=3.0.0-beta.4"
actix-http = "=3.0.0-beta.4" # FIXME: temporary intermediate
actix-web = "=4.0.0-beta.4" # we need v4 as we need tokio 1
actix-web-httpauth = "0.6.0-beta.1"
actix-web-actors = "4.0.0-beta.3"

futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"

reqwest = { version = "0.11", features = ["json"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

uuid = { version = "0.8", features = ["v4"] }
percent-encoding = "2"
http = "0.2"

env_logger = "0.7"
log = "0.4"

cloudevents-sdk = "0.4"
cloudevents-sdk-actix-web = "0.4"

drogue-cloud-endpoint-common = { path = "../endpoint-common" }
drogue-cloud-service-api = { path = "../service-api" }
drogue-cloud-service-common = { path = "../service-common" }

drogue-client = "0.5.0-alpha.3"
drogue-ttn = "0.4"

dotenv = "0.15.0"
config = "0.10"
envconfig = "0.9"
jsonwebtokens = "1.0.0-alpha.13"
mime = "0.3"

tokio = { version = "1", features = ["full"] }

openid = "0.9"

chrono = "0.4"

[dependencies.rust-tls]
version = "0.19"
package = "rustls"

[dependencies.open-ssl]
version = "0.10"
package = "openssl"
features = ["v111"]

[features]
default = ["openssl"]
openssl = ["actix-web/openssl"]
rustls = ["actix-web/rustls"]
