kind: Deployment
apiVersion: apps/v1
metadata:
  name: user-auth-service
spec:
  template:
    spec:
      containers:
        - name: service
          env:
            - name: "KEYCLOAK__TLS_NOVERIFY"
              value: "true"
