kind: Kafka
apiVersion: kafka.strimzi.io/v1beta1
metadata:
  name: kafka-eventing
spec:
  kafka:
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
  zookeeper:
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
