[workspace]

members = [
    "endpoint-common",
    "http-endpoint",
    "mqtt-endpoint",
    "console-common",
    "console-backend",
    "console-frontend",
    "authentication-service",
    "device-management-service",
    "database-common",
    "service-common",
    "service-api",
    "command-endpoint",
    "test-common",
    "registry-events",
    "outbox-controller",
]

[patch.crates-io]
testcontainers = { git = "https://github.com/testcontainers/testcontainers-rs", rev = "fe51e06fb2c44b1d3e3fd627cedea3fd582487ef" }
#ntex-mqtt = { path = "../ntex-mqtt" }
#patternfly-yew = { path = "../patternfly-yew" }
#patternfly-yew = { git = "https://github.com/ctron/patternfly-yew", branch = "main" }
#drogue-ttn = { path = "../drogue-ttn" }
#diesel = { git = 'https://github.com/diesel-rs/diesel', rev = "06494e8bdfe774bac9be5cab488b3d0cbec97f4e" }
#openid = { git = "https://github.com/ctron/openid.git", branch = "feature/custom_ca_1" }
#actix-cors = { git = "https://github.com/ctron/actix-extras", rev = "8718685f0237ac8cf39c8f73a272bd1d7205ba8e" }
#actix-web-httpauth = { git = "https://github.com/ctron/actix-extras", rev = "8718685f0237ac8cf39c8f73a272bd1d7205ba8e" }
#reqwest = { git = "https://github.com/ctron/reqwest", branch = "feature/basic_auth_wasm_1" }

#actix-cors = { path = "../actix-extras/actix-cors" }
#actix-web-httpauth = { path = "../actix-extras/actix-web-httpauth" }

actix-cors = { git = "https://github.com/ctron/actix-extras", rev = "a580096e7c7e929ac9b6b77abee7403890006e0a" }
actix-web-httpauth = { git = "https://github.com/ctron/actix-extras", rev = "a580096e7c7e929ac9b6b77abee7403890006e0a" }

#cloudevents-sdk = { path = "../sdk-rust" }
#cloudevents-sdk-actix-web = { path = "../sdk-rust/cloudevents-sdk-actix-web" }
#cloudevents-sdk-reqwest = { path = "../sdk-rust/cloudevents-sdk-reqwest" }
#cloudevents-sdk-rdkafka = { path = "../sdk-rust/cloudevents-sdk-rdkafka" }

cloudevents-sdk = { git = "https://github.com/ctron/sdk-rust", rev = "66ffe07a16fb7bac780a24f31042eed564514301" }
cloudevents-sdk-actix-web = { git = "https://github.com/ctron/sdk-rust", rev = "66ffe07a16fb7bac780a24f31042eed564514301" }
cloudevents-sdk-reqwest = { git = "https://github.com/ctron/sdk-rust", rev = "66ffe07a16fb7bac780a24f31042eed564514301" }
cloudevents-sdk-rdkafka = { git = "https://github.com/ctron/sdk-rust", rev = "66ffe07a16fb7bac780a24f31042eed564514301" }
