[package]
name = "drogue-cloud-service-api"
version = "0.4.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"

[dependencies]

log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
async-trait = "0.1"
indexmap = { version = "1", features = ["serde"] }

base64 = "0.13"
base64-serde = "0.6"
chrono = { version = "0.4", features = ["serde"] }

url = "2"

drogue-client = "0.5.0-alpha.1"