apiVersion: eventing.knative.dev/v1alpha1
kind: KnativeEventingKafka
metadata:
  name: knative-eventing-kafka
  namespace: knative-eventing
spec:
  bootstrapServers: kafka-eventing-kafka-bootstrap.knative-eventing.svc:9092
  setAsDefaultChannelProvisioner: true
