apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: influxdb-pusher
spec:
  template:
    spec:
      containers:
        - image: quay.io/drogueiot/influxdb-pusher:latest
#        - image: image-registry.openshift-image-registry.svc:5000/drogue-iot/influxdb-pusher:latest
          env:
            - name: RUST_LOG
              value: info
            - name: INFLUXDB_URI
              value: http://influxdb:8086
            - name: INFLUXDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: influxdb-config
                  key: databaseName
            - name: INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: app.username
            - name: INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: app.password
