apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: influxdb-kafka-source
spec:
  consumerGroup: influxdb-pusher
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  topics:
    - knative-messaging-kafka.drogue-iot.iot-channel
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: influxdb-pusher
