apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client
  labels:
    app.kubernetes.io/part-of: console
spec:
  realmSelector:
    matchLabels:
      app.kubernetes.io/part-of: console
  client:
    clientId: drogue
    clientAuthenticatorType: client-secret
    enabled: true
    rootUrl: ""
    publicClient: false
    implicitFlowEnabled: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: true
    fullScopeAllowed: false
    redirectUris:
      - "http://not-yet-set"
    defaultRoles:
      - "drogue-user"
      - "drogue-admin"
    protocolMappers:
      - name: add-audience
        protocol: openid-connect
        protocolMapper: oidc-audience-mapper
        consentRequired: false
        config:
          "included.client.audience": "drogue"
          "id.token.claim": "false"
          "access.token.claim": "true"
