openapi: "3.0.0"
info:
  title: Drogue Cloud API
  version: "0.5"
  contact:
    url: https://drogue.io
servers:
  - url: "http://localhost:8080"
externalDocs:
  description: Drogue Cloud Documentation
  url: https://book.drogue.io
security:
  - api_key: []
paths:
  "/.well-known/drogue-version":
    get:
      description: "Get version"
      responses:
        "200":
          description: "Version response"
          content:
            "application/json":
              schema:
                type: object
                properties:
                  success:
                    type: string
                    enum: ["true"]
                required:
                  - success
  "/api/keys/v1alpha1":
    get:
      description: List API keys for this user.
      responses:
        "200":
          description: All API keys for this user.
          content:
            "application/json":
              schema:
                type: array
                items:
                  type: object
                  properties:
                    created:
                      type: string
                      format: date-time
                    prefix:
                      type: string
    post:
      description: Create a new API key for this user.
      responses:
        "200":
          description: A new API key was created.
          content:
            "application/json":
              schema:
                type: object
                properties:
                  key:
                    type: string
                  prefix:
                    type: string
                required:
                  - key
                  - prefix
  "/api/keys/v1alpha1/{prefix}":
    delete:
      description: Delete an API key by prefix.
      parameters:
        - name: prefix
          required: true
          in: path
          description: The prefix of the API key to delete.
      responses:
        "204":
          description: |
            Successfully delete API key.

            If the API key didn't exists, still 204 will be returned.

components:
  securitySchemes:
    api_key:
      type: oauth2
      description: Log in using your Drogue Cloud account
      flows:
        implicit:
          authorizationUrl: "https://keycloak-drogue-dev.apps.wonderful.iot-playground.org/auth/realms/drogue/protocol/openid-connect/auth"
          scopes:
            openid: OpenID Connect
