kind: Service
apiVersion: v1
metadata:
  name: mqtt-integration
  labels:
    app.kubernetes.io/name: mqtt-integration
    app.kubernetes.io/part-of: integrations
spec:
  selector:
    app.kubernetes.io/name: mqtt-integration
    app.kubernetes.io/part-of: integrations
  ports:
    - name: endpoint
      protocol: TCP
      port: 443
      targetPort: endpoint
