[package]
name = "drogue-cloud-console-frontend"
version = "0.2.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
description = "Console Frontend"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"

drogue-cloud-console-common = { path = "../console-common" }

yew = "0.17"
yew-router = "0.14"
patternfly-yew = "0.0.10"

wasm-bindgen = "0.2"

js-sys = "0.3"
web-sys = { version = "0.3", features = ["EventSource", "EventSourceInit", "Window", "Location"] }

once_cell = "1"

chrono = { version = "0.4", features = ["wasmbind"] }
chrono-tz = "0.5"

url = "2"
http = "0.2"

cloudevents-sdk = "0.3"

log = "0.4"
wasm-logger = "0.2"

headers = "0.3"

serde = "1"
serde_json = "1"

unicode-segmentation = "1"
pretty-hex = "0.2"
base64 = "0.13"
itertools = "0.9"

[dev-dependencies]
env_logger = "0.7"
