kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqtt-integration
spec:
  to:
    kind: Service
    name: mqtt-integration
  port:
    targetPort: endpoint
  tls:
    termination: passthrough
