kind: Service
apiVersion: v1
metadata:
  name: http-endpoint
  labels:
    app.kubernetes.io/name: http-endpoint
    app.kubernetes.io/part-of: endpoints
spec:
  selector:
    app.kubernetes.io/name: http-endpoint
    app.kubernetes.io/part-of: endpoints
  ports:
    - name: endpoint
      protocol: TCP
      port: 443
      targetPort: endpoint
