[package]
name = "coap-endpoint"
version = "0.1.0"
authors = ["Pranav <adpranavb2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coap = {version = "0.9", path = "/home/pranav/Desktop/jboss/coap-rs"}
coap-lite = "0.4"
cloudevents-sdk = "^0.4"
cloudevents-sdk-coap = {version = "0.1", path = "/home/pranav/Desktop/jboss/cloudevents-sdk-coap"}
tokio = "1.7"
anyhow = "1"
drogue-cloud-endpoint-common = { path = "../endpoint-common" }
drogue-cloud-service-api = { path = "../service-api" }
drogue-cloud-service-common = { path = "../service-common" }
drogue-client = "0.5.0"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded= "^0.7"
bytes = "1"
bytestring = "1"
log = "^0.4"
env_logger = "0.7"
dotenv = "0.15"
futures = "0.3"
http = "0.2"
