apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base/service/console/

patchesStrategicMerge:
  - deployment-backend.yaml
  - service-backend.yaml
  - service-frontend.yaml
