[package]
name = "drogue-cloud-test-common"
version = "0.1.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
log = "0.4"
testcontainers = "0.11"
deadpool = "0.7"
deadpool-postgres = "0.7"
walkdir = "2"
