[package]
name = "drogue-cloud-database-common"
version = "0.2.0"
authors = ["Jean-Baptiste Trystram <jbtrystram@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

async-trait = "0.1"
log = "0.4"
thiserror = "1"

actix-web = "4.0.0-beta.1" # we need v4 as we need tokio 1

serde_json = "1"
serde = "1"

deadpool = "0.7"
deadpool-postgres = { version = "0.7", features = ["config"] }
tokio-postgres = { version = "0.7", features = ["runtime", "with-serde_json-1"] }

drogue-cloud-service-api = { path = "../service-api" }

[dev-dependencies]
anyhow = "1"