[package]
name = "drogue-cloud-database-common"
version = "0.1.0"
authors = ["Jean-Baptiste Trystram <jbtrystram@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

diesel = { version = "2.0.0", features = ["postgres", "r2d2", "serde_json"] }
serde_json = "1"
serde = "1"
actix-web = "3"
log = "0.4"