apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/sso

resources:
  - service.yaml
  - ingress.yaml

patchesJson6902:
- target:
    group: keycloak.org
    version: v1alpha1
    kind: Keycloak
    name: sso
  path: instance_patch.yaml
