[package]
name = "drogue-cloud-service-common"
version = "0.1.0"
authors = ["Jean-Baptiste Trystram <jbtrystram@redhat.com>"]
edition = "2018"

[dependencies]

envconfig = "0.9"
log = "0.4"
config = "0.10"
anyhow = "1"

actix-http = "=3.0.0-beta.4" # FIXME: temporary intermediate
actix-web = "=4.0.0-beta.4" # we need v4 as we need tokio 1
actix-web-httpauth = "=0.6.0-beta.1"
actix-service = "=2.0.0-beta.4"

reqwest = "0.11"
openid = "0.8"

failure = "0.1" # required for converting error away from failure
url = "2"
pem = "0.8"
chrono = "0.4"
humantime = "2"
humantime-serde = "1"

serde = "1"
serde_json = "1"
thiserror = "1"

async-std = "1.9"
async-trait = "0.1"
futures = "0.3"

kube = "0.51"
kube-derive = "0.51"
k8s-openapi = { version = "0.11", features = ["v1_17"] }
openshift-openapi = { version = "0.3", features = ["v4_4"] }

cloudevents-sdk = "0.4"

drogue-cloud-service-api = { path = "../service-api" }

[dev-dependencies]
env_logger = "0.8"
tokio = { version = "1", features = ["full"] }