apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: device-management-service
  labels:
    image-source: build
    app.kubernetes.io/name: device-management-service
    app.kubernetes.io/part-of: device-registry
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"postgres"}]'
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/drogue-iot/device-management-service:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: info
            - name: ENABLE_AUTH
              value: "false"
            - name: BIND_ADDR
              value: 0.0.0.0:8080
            - name: A_POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: databaseName
            - name: A_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: admin.username
            - name: A_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: admin.password
            # DATABASE_URL must only reference variables which are sorted before `D...`
            # see: https://github.com/knative/client/issues/1165
            - name: DATABASE_URL
              value: postgres://$(A_POSTGRES_USER):$(A_POSTGRES_PASSWORD)@postgres/$(A_POSTGRES_DB)
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
