apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#images:
#- name: ghcr.io/drogue-iot/http-endpoint
#  newname: quay.io/dejanb/http-endpoint

bases:
  - ../base/knative
  - sso
  - ../base/source/http
  - source/mqtt
  - ../base/service/influxdb
  - service/grafana
  - service/console
  - ../base/service/registry
