kind: Deployment
apiVersion: apps/v1
metadata:
  name: authentication-service
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"postgres"}]'
  labels:
    app.kubernetes.io/name: authentication-service
    app.kubernetes.io/part-of: device-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authentication-service
      app.kubernetes.io/part-of: device-registry
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentication-service
        app.kubernetes.io/part-of: device-registry
    spec:
      containers:
        - name: service
          image: ghcr.io/drogue-iot/authentication-service:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: info
            - name: BIND_ADDR
              value: 0.0.0.0:8080
            - name: PG__HOST
              value: postgres
            - name: PG__DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: databaseName
            - name: PG__USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: admin.username
            - name: PG__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: admin.password
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 8080
              path: /health
          ports:
            - containerPort: 8080
              name: api
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
