kind: Deployment
apiVersion: apps/v1
metadata:
  name: console-frontend
  labels:
    app: console-frontend
    image-source: build
    app.kubernetes.io/part-of: console
spec:
  replicas: 1
  selector:
    matchLabels:
      image-source: build
      app: console-frontend
  template:
    metadata:
      labels:
        image-source: build
        app: console-frontend
    spec:
      containers:
        - name: endpoint
          image: ghcr.io/drogue-iot/console-frontend:latest
          imagePullPolicy: Always
          env:
# Needs to be set, is done by 'drogue.sh'
#            - name: BACKEND_URL
#              value: https://console-backend-$(NAMESPACE).$(CLUSTER_DOMAIN)
          ports:
            - containerPort: 8080
              name: endpoint
              protocol: TCP
          resources:
            limits:
              memory: 64Mi
          volumeMounts:
            - mountPath: /run
              name: run
            - mountPath: /endpoints
              name: endpoints
      volumes:
        - name: run
          emptyDir: {}
        - name: endpoints
          emptyDir: {}