kind: Deployment
apiVersion: apps/v1
metadata:
  name: console-backend
  labels:
    image-source: build
    app: console-backend
    app.kubernetes.io/part-of: console
spec:
  replicas: 1
  selector:
    matchLabels:
      image-source: build
      app: console-backend
  template:
    metadata:
      labels:
        image-source: build
        app: console-backend
    spec:
      serviceAccountName: console-backend
      initContainers:
        - name: wait-for-client-secret
          image: registry.access.redhat.com/ubi8-minimal
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -c
            - |
              echo "Waiting for client secret to be populated (/etc/client-secret/CLIENT_SECRET)..."
              while test -z "$(cat /etc/client-secret/CLIENT_SECRET)"; do
                sleep 1
              done
          volumeMounts:
            - mountPath: /etc/client-secret
              name: client-secret
              readOnly: true
      containers:
        - name: endpoint
          image: ghcr.io/drogue-iot/console-backend:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: info
            - name: BIND_ADDR
              value: "0.0.0.0:8080"
            - name: ENABLE_AUTH
              value: "true"
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-drogue
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-drogue
                  key: CLIENT_SECRET
          ports:
            - containerPort: 8080
              name: endpoint
              protocol: TCP
          resources:
            limits:
              memory: 64Mi
      volumes:
        - name: client-secret
          secret:
            secretName: keycloak-client-secret-drogue