apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: push-test-pipeline
spec:

  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: branch-name
      type: string
      description: The git branch to clone.

  workspaces:
    - name: shared-data

  tasks:

    - name: init
      taskRef:
        name: build-metadata

    - name: cargo-build
      runAfter: ["init"]
      taskSpec:
        steps:
          - name: cargo-build
            image: registry.access.redhat.com/ubi8-minimal
            workingDir: $(workspaces.source.path)
            script: |
              mkdir -p target/release
              touch target/release/web-test
        workspaces:
          - name: source
      workspaces:
        - name: source
          workspace: shared-data

    - name: container-build
      runAfter: ["cargo-build"]
      taskRef:
        name: buildah
      params:
        - name: DOCKERFILE
          value: web-test/Dockerfile
        - name: IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/$(tasks.init.results.namespace)/web-test:latest"
        - name: TLSVERIFY
          value: "false" # required for now, to push to internal registry
      workspaces:
        - name: source
          workspace: shared-data
