apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-endpoint
  labels:
    app.kubernetes.io/name: command-endpoint
    app.kubernetes.io/part-of: endpoints
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: command-endpoint
      app.kubernetes.io/part-of: endpoints
  template:
    metadata:
      labels:
        app.kubernetes.io/name: command-endpoint
        app.kubernetes.io/part-of: endpoints
    spec:
      containers:
        - name: endpoint
          image: ghcr.io/drogue-iot/command-endpoint:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: debug
            - name: BIND_ADDR
              value: "0.0.0.0:8080"
          ports:
            - containerPort: 8080
              name: endpoint
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
