kind: Service
apiVersion: v1
metadata:
  name: command-endpoint
  labels:
    app: command-endpoint
spec:
  selector:
    app: command-endpoint
  ports:
    - name: endpoint
      protocol: TCP
      port: 443
      targetPort: endpoint
