apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: command-endpoint
  labels:
    image-source: build
    app.kubernetes.io/part-of: endpoints
spec:
  template:
    metadata:
      labels:
        image-source: build
        bindings.knative.dev/include: "true"
    spec:
      containers:
        - image: ghcr.io/drogue-iot/command-endpoint:latest
          env:
            - name: RUST_LOG
              value: info
