apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#images:
#- name: ghcr.io/drogue-iot/mqtt-endpoint
#  newname: quay.io/dejanb/mqtt-endpoint

bases:
  - ../base/configuration
  - ../base/knative
  - ../base/sso
  - source/mqtt
  - source/http
  - source/command
  - ../base/service/influxdb
  - service/grafana
  - service/console
  - service/registry
  - integration/mqtt