kind: Deployment
apiVersion: apps/v1
metadata:
  name: mqtt-endpoint
  labels:
    image-source: build
    app: mqtt-endpoint
    app.kubernetes.io/part-of: endpoints
spec:
  replicas: 1
  selector:
    matchLabels:
      image-source: build
      app: mqtt-endpoint
  template:
    metadata:
      labels:
        image-source: build
        app: mqtt-endpoint
    spec:
      containers:
        - name: endpoint
          image: ghcr.io/drogue-iot/mqtt-endpoint:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: info
            - name: BIND_ADDR_MQTT
              value: "0.0.0.0:8883"
            - name: BIND_ADDR_HTTP
              value: "0.0.0.0:8080"
            - name: CERT_FILE
              value: /etc/endpoint/tls.crt
            - name: KEY_FILE
              value: /etc/endpoint/tls.key
            - name: AUTH_SERVICE_URL
              value: http://authentication-service:8080
          ports:
            - containerPort: 8883
              name: endpoint
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 64Mi
          volumeMounts:
            - mountPath: /etc/endpoint
              name: endpoint-tls
      volumes:
        - name: endpoint-tls
          secret:
            secretName: mqtt-endpoint-tls
