name: CI

on:
  push:
    # Must only run on branches that we want to publish
    branches:
      - main
  # Can run on PRs, as we don't publish when building a PR
  pull_request:

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            .cargo-container-home
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get -y install libsasl2-dev

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check

  build:
    name: build and deploy
    runs-on: ubuntu-20.04
    needs: [check]
    env:
      CLUSTER: "kind"
    steps:

      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            .cargo-container-home
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get -y install libsasl2-dev

      - name: Run build
        run: |
          make build

      - name: Run tests
        run: |
          make test

      - uses: docker/setup-buildx-action@v1

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-cache-ci

      #todo : move this step from the makefile to the CI makefile.
      - name: Fix permissions
        run: make fix-permissions

      - name: Build images
        run: make -C .github/scripts build-images-ci

      # todo put dev.local into a variable.
      # "dev.local" prefixed images won't be resolved by the knative operator
      - name: Tag images
        run: make tag-images IMAGE_TAG=${{ github.sha }} CONTAINER_REGISTRY=dev.local

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          wait: 300s
          cluster_name: kind

      - name: load images in Kind
        run: make -C .github/scripts kind-load-images IMAGE_TAG=${{ github.sha }} CONTAINER_REGISTRY=dev.local

      - name: Update image names
        run: |
          mkdir tmp
          ./hack/replace-images.py ${{ github.sha }} IfNotPresent deploy dev.local tmp/deploy

      - name: Deploy drogue
        run: ./hack/drogue.sh -d tmp/deploy
        timeout-minutes: 20

      - name: Collect logs
        if: failure()
        run: |
          kubectl get deployments -n drogue-iot -l '!serving.knative.dev/service'
          ./.github/scripts/collect_logs.sh /tmp drogue-iot

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: drogue-iot-logs
          path: /tmp/logs
