name: CI

on:
  push:
    # Must only run on branches that we want to publish
    branches:
      - main
  # Can run on PRs, as we don't publish when building a PR
  pull_request:

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.49 # must be aligned with the builder image
          components: rustfmt, clippy
          profile: minimal
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get -y install libsasl2-dev

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release

      - name: Clippy check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --release --all-features


  test:
    name: run tests
    runs-on: ubuntu-20.04
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.49 # must be aligned with the builder image
          profile: minimal
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get -y install libsasl2-dev

      - name: Run tests
        run: |
          # single thread because of the database
          # nocapture to see the logs
          make container-test CARGO_TEST_OPTS="--nocapture"

  build:
    name: build
    runs-on: ubuntu-20.04
    needs: [check]
    steps:

      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            .cargo-container-home
            target
          key: ${{ runner.os }}-cargo-container-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/cache@v2
        with:
          path: console-frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('console-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch


      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.49 # must be aligned with the builder image
          profile: minimal
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get -y install libsasl2-dev

      - name: Run build
        run: |
          make build

      - name: Fix permissions
        run: make fix-permissions

      - uses: docker/setup-buildx-action@v1

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ steps.extract_branch.outputs.branch }}

      - id: cache-docker
        uses: actions/cache@v1
        with:
          path: /tmp/docker-registry
          key: docker-registry-${{ steps.extract_branch.outputs.branch }}

      - run: docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2

      # Pull previous images
      - run: make  -C .github/scripts pull-images CONTAINER_REGISTRY=localhost:5000 || true

      - name: Build images
        run: make -C .github/scripts build-images-ci

      # Push images in local registry
      - run: make push CONTAINER_REGISTRY=localhost:5000

  deploy:
    name: deploy drogue on Kind
    runs-on: ubuntu-20.04
    needs: [check, build]
    env:
      CLUSTER: "kind"
    steps:

      - id: cache-docker
        uses: actions/cache@v1
        with:
          path: /tmp/docker-registry
          key: docker-registry-${{ steps.extract_branch.outputs.branch }}

      - run: docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2

      # Pull and tag previous images
      - run: make pull-images CONTAINER_REGISTRY=localhost:5000 || true

      # todo put dev.local into a variable.
      # "dev.local" prefixed images won't be resolved by the knative operator
      - name: Tag images
        run: make tag-images IMAGE_TAG=${{ github.sha }} CONTAINER_REGISTRY=dev.local

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          wait: 300s
          cluster_name: kind

      - name: load images in Kind
        run: make -C .github/scripts kind-load-images IMAGE_TAG=${{ github.sha }} CONTAINER_REGISTRY=dev.local

      - name: Update image names
        run: |
          mkdir tmp
          # A policy of "Always" is not going to work, as the images are pushed into the kind cluster
          # and cannot be pulled. Using "Always" would result in attempts to try to pull from a location
          # that does not exist.
          ./hack/replace-images.py ${{ github.sha }} Never deploy dev.local tmp/deploy

      - name: Deploy drogue
        run: env TEST_CERTS_IMAGE=dev.local/test-cert-generator:${{ github.sha }} ./hack/drogue.sh -d tmp/deploy
        timeout-minutes: 20

      - name: Collect logs
        if: failure()
        run: ./.github/scripts/collect_logs.sh /tmp drogue-iot

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: drogue-iot-logs
          path: /tmp/logs
